<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>7f7f73c2-1014-4a6c-bb4b-21415e7c4a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;language-list-select&quot;]//input[@name='chk_language'][count(. | //*[@ref_element = 'Object Repository/1_Actions_AppSpecific/2_Content Studio/3_Publisher/iframe_main-iframe']) = count(//*[@ref_element = 'Object Repository/1_Actions_AppSpecific/2_Content Studio/3_Publisher/iframe_main-iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language-list-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;language-list-select&quot;]//input[@name='chk_language']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catalogLibrarySelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/1_Actions_AppSpecific/2_Content Studio/3_Publisher/iframe_main-iframe</value>
   </webElementProperties>
</WebElementEntity>
