<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_toggleForEssentialSMECust</name>
   <tag></tag>
   <elementGuidId>4c610533-f3da-4734-af92-89baf77ebc3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id=&quot;launch-option-customerSMEEssentials&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@id=&quot;launch-option-customerSMEEssentials&quot;]</value>
   </webElementProperties>
</WebElementEntity>
