<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_content_studio_main</name>
   <tag></tag>
   <elementGuidId>14817011-bdfe-4704-8a39-f148cc2ea261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content-studio-main-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='content-studio-main-iframe']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'content-studio-main-iframe' and @src = 'csApp.0.1.02.rev.71.20210218/main-contentstudio.html']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content-studio-main-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>csApp.0.1.02.rev.71.20210218/main-contentstudio.html</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-studio-main-iframe&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='content-studio-main-iframe']</value>
   </webElementXpaths>
</WebElementEntity>
